# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-07 06:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('title', models.CharField(max_length=200)),
                ('company_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
